### ISSUE TITLE
convex as a blockchain backend for sign-in like magic.link?

### ISSUE THREAD

**Issue by WorldsEndless** [Convex-Dev/convex#500]
As a Clojurian I have followed Convex with great interest, but never set aside the time to figure it out. I am totally new to blockchain/crypto concerns but was shocked when an app I am building started failing its magic.link authentication all because apparently magic.link has gone over to complete blockchain infrastructure; the magic quickstart guide is at https://magic.link/docs/connect/getting-started/quickstart and reveals that it intends to be backed by either web3.js or ethereum. I was about to give up on it altogether when I remembered the Convex project and started to wonder if it could be used as a replacement within magic.link. I am also open to any other recommended Convex-compatible login solution that might be simple enough for my full-stack Clojure project.

What will it take to get a passwordless user sign-in solution using Convex?

**Comment by mikera** [comment]
I'm not really familiar with magic.link or quite sure precisely what you mean by "passwordless user sign-in solution". The answer is probably "It's pretty easy" but would need to know some more specifics. Maybe best to discuss on Discord, others may have ideas?
https://discord.com/invite/xfYGq4CT7v

Fundamentally though, you don't need any password / user identity to make use of Convex. There are two types of interactions that may be of interest:

- **Queries** (which read or compute values from the global state) are essentially free, you just need a Peer willing to serve these up to users on a permission less basis
- **Transactions** which modify the global state must pay a small fee (negligible for practical purposes, but necessary to prevent DoS attacks) and perform one valid Ed25519 signature. Services could optional pay the transaction fees and provide custody for Ed25519 keys for their users (this might make sense if you are building a full-stack solution).

**Comment by mikera** [comment]
Closing this here because it's not really a Convex core issue (more a question for wallet providers) but I do think it would be great to get a truly decentralised, self-custodial wallet solution going on Convex and/or the Lattice.

One idea: if you want a ID / login solution:
- ask for a Convex account number (e.g. `#15675`) or CNS name (e.g. `@user.mike`)
- Server queries Convex to get the `*key*` for the account which will be a 32-byte Ed25519 public key
- Server send a random challenge message to client and asks client to sign it
- Server checks the signature with Ed25519. If valid, you know the user has the private key to the given account and can proceed. User can presumably also sign other Convex transactions at this point (e.g. token transfers, smart contract calls etc.)
